### ISSUE TITLE
ActionController::InvalidAuthenticityToken in UsersController#create

### ISSUE THREAD

**Issue by CaryLynch** [CaryLynch/projectFour#2]
Hey Neel. So, I had my create new user form working great. I created a new user account, and I checked it to the database and it was there. I also checked it by using the email and password to then login, and it worked. I then added all of the migrations for all the tables in the database. I realized that when I ran the migrations, it added the tables to my schema, but it had not added the column info from the migrations files. So, I dropped the db, recreated, reran the migration and everything was set up fine in the database with all of the tables and columns for each. So I tried creating an account again in the browser, and it's now giving me this error: ActionController::InvalidAuthenticityToken in UsersController#create.

I did not change anything at all in any of the controllers after it was working, so I don't know why it stopped working. Everything is pushed if you wanna take a look. I feel confident that I have all the authenticity code that I need.

**Comment by darthneel** [comment]
Hey Cary, I took a look at the code and it seems to be alright. Are you still receiving this error?

**Comment by CaryLynch** [comment]
Hey Neel. Sorry I'm just getting back to you. I'm just getting in from an allergist appointment this morning. So, yeah, I just restarted the server and tried again, and I'm still having the same issue.
