### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by CaryLynch** [CaryLynch/projectFour#4]
could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

Above is the error. 
Everything was working just fine last night. I closed my computer and when I got here this am, my computer was acting glitchy in general so I restarted it. Now I'm getting this error. I googled it and it seems to have something to do with sockets and permissions...? I'm not sure about this. I don't understand how it went from working to not working, when I hadn't touched the code since the last time it was working.

**Comment by CaryLynch** [comment]
this is the full error:

PG::ConnectionBad (could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

**Comment by darthneel** [comment]
I think this is an issue with postgres launch control. Fritz is our resident postgres error fixer. I'm going to ask him for some help on how to fix this and let you know.

**Comment by CaryLynch** [comment]
This is definitely some kind of issue with postgres. I'll be honest, I'm a little too nervous to attempt to fix it myself, based on the stackoverflow answers. I'd have no idea what I'm doing.

**Comment by CaryLynch** [comment]
Got any idea when I'll be able to see Fritz? This issue is holding me up from being able to do just about everything.
