### ISSUE TITLE
Persisting to the database

### ISSUE THREAD

**Issue by CaryLynch** [CaryLynch/projectFour#7]
Morning Neel! 

So, I got a  couple more things done last night, but I'm a bit confused still about persisting to the database. What I am trying to persist (causes and deeds) are both through a join table. Users will have causes through the interests table and users will have deeds through users_deeds. But I only have routes for users, causes and deeds- which means I don't have a route or controller for the join tables. So, I am trying to make the logic for creating new deeds for the user in the deed controller/create method. But this logic is not making sense to me, as I feel like I should be referencing an instance of users_deeds instead of deeds. Can we talk about this? I want to get the logic to work so I can move on to styling this afternoon. 
Thanks. 
ps- I was able to get the organizations for each cause to render to the cause/id page!! WooWoo!

**Comment by darthneel** [comment]
Hey Cary, can you meet me up on 4 to discuss?

**Comment by CaryLynch** [comment]
Hey!
Yes I can. Be there in a minute.
