### ISSUE TITLE
Last ditch effort for committing deeds

### ISSUE THREAD

**Issue by CaryLynch** [CaryLynch/projectFour#8]
Hey Neel. I've done so much work, but I'm still having trouble persisting the deeds. The causes persist, but not the deeds. I think I just need a second pair of eyes. I did end up adding a show page for the deeds, and I'm trying to figure out how to list the organizations for each deed. But right now when I try to persist (post to users/id/deeds) I get an error: 
Unable to autoload constant Users_deed, expected /Users/macbook1/dev/wdi/projectFour/allGoodDeeds/app/models/users_deed.rb to define it

Honestly, just not sure. Help?

**Comment by darthneel** [comment]
I feel like its an issue with your file name, but come up right now and I'll take a look at it.
